apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: laravel
resources:
  - namespace.yaml
  - configmap-app.yaml
  - secret-app.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
