apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-storage
  namespace: laravel
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""  # Set your StorageClass, e.g. "standard"
